#单机注册中心
eureka:
  client:
    #单机需要配置为flase
    fetch-registry: false
    # 由于该应用为注册中心，如果设置成false，代表不向注册中心注册自己。 #单机需要配置为flase
    register-with-eureka: false
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@localhost:17001/eureka-server/eureka/


